### PR TITLE
Banking system

### LINKED ISSUE #4: Banking system
Create a simple banking system using inheritance in C++. The app provides different types of accounts and various options currency-wise.

Requirements:
- [x] creating accounts
- [x] depositing money
- [x] withdrawing money
- [x] option to check bank account (First name, Last name, Money) 
- [x] CLI for data input
- [x] use smart pointers
- [x] add exception handling

### PR DESCRIPTION
**Pull request by eggwhat**
The functionality should be implemented. Some refactoring would be nice. Unfortunately the application doesn't provide exception handling yet, so please specify reasonable input.

How to use command line interface:
- first create a user profile
- then list clients and choose a client by ID
- after choosing a client there is an option for creating a new account for such client or interacting with an existing one (for premium account there is an option for choosing a currency that this account will be using)
- after choosing an existing account by its number there is an option for displaying account details, depositing and withdrawing money

### CODE REVIEW

File: banking_system/command_line_interface.cpp [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+        std::cout << "Provide a first name:" << std::endl;
+        std::cin >> firstName;
+        std::cout << "Provide a middle name:" << std::endl;
+        std::cin >> middleName;
+        std::cout << "Provide a last name:" << std::endl;
+        std::cin >> lastName;
+        maintenance.addClient(std::make_shared<bank::Person>(firstName, middleName, lastName));
+    }
+
+    void CommandLineInterface::depositMoney(std::unique_ptr<bank::IManager> const& accountManager, std::shared_ptr<bank::IAccount> const& account) {
```
Comment (IllidanSR) [inline banking_system/command_line_interface.cpp]: Let's avoid here to use reference to unique_ptr and use const reference instead, or return value from method maybe?

File: banking_system/command_line_interface.cpp [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+                }
+                else {
+                    manager = standardAccountManagerFactory.createManager();
+                    funds = std::make_unique<bank::FundsEUR>(0.0);
+                }
+                maintenance.addAccount(manager->createAccount(client, std::move(funds)));
+            }
+            case 2: {
+                std::cout << "Client accounts: " << std::endl;
+                auto accounts = maintenance.findClientAccounts(clientId);
```
Comment (IllidanSR) [inline banking_system/command_line_interface.cpp]: const?

File: banking_system/command_line_interface.cpp [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+                bank::Maintenance::listClientAccount(accounts);
+                std::cout << "Choose account: " << std::endl;
+                unsigned int accountIndex;
+                std::cin >> accountIndex;
+                int accountOption;
+                auto account = accounts[accountIndex];
```
Comment (IllidanSR) [inline banking_system/command_line_interface.cpp]: const

File: banking_system/command_line_interface.cpp [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+                        std::cout << "Invalid option. Please try again." << std::endl;
+                        break;
+                }
+                break;
+            }
+            default:
+                break;
+        }
+    }
+} // bank_cli
```
Comment (IllidanSR) [inline banking_system/command_line_interface.cpp]: new line

File: banking_system/funds_pln.h [hunk 5]
```diff
@@ -0,0 +1,16 @@
+#pragma once
+
+#include "i_funds.h"
+
+namespace bank {
+    class FundsPLN: public IFunds {
+
+    public:
+        explicit FundsPLN(double const _amountOfMoney): IFunds(_amountOfMoney) {}
```
Comment (IllidanSR) [inline banking_system/funds_pln.h]: amountOfMoney - for function/method/constructor arguments
_amountOfMoney - for private fields

File: banking_system/i_account.h [hunk 6]
```diff
@@ -0,0 +1,30 @@
...
+        explicit IAccount(std::shared_ptr<Person> person, std::unique_ptr<IFunds> funds):
+            m_person(std::move(person)), m_funds(std::move(funds)) {}
+        virtual ~IAccount() = default;
+
+        enum class AccountType { Standard, Premium };
+        AccountType accountType;
+
+        unsigned int getUserId() const { return m_person->id; }
+        void depositMoney(double const money) const { m_funds->depositMoney(money); }
+        void withdrawMoney(double const money) const { m_funds->withdrawMoney(money); }
```
Comment (IllidanSR) [inline banking_system/i_account.h]: Better option - avoid to have implementation inside interface.

File: banking_system/i_account.h [hunk 7]
```diff
@@ -0,0 +1,30 @@
...
+
+        virtual std::string getDetails() = 0;
+    protected:
+        std::shared_ptr<Person> m_person;
+        std::unique_ptr<IFunds> m_funds;
```
Comment (IllidanSR) [inline banking_system/i_account.h]: As well, better option - avoid have fields inside interface

File: banking_system/i_funds.h [hunk 8]
```diff
@@ -0,0 +1,29 @@
...
+
+#include <string>
+#include <iostream>
+
+namespace bank {
+    class IFunds {
+    private:
+        double amountOfMoney;
+    public:
+        explicit IFunds(double const _amountOfMoney): amountOfMoney(_amountOfMoney) {}
```
Comment (IllidanSR) [inline banking_system/i_funds.h]: For interface we should have no possibility to call constructor.

File: banking_system/maintenance.cpp [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+    void Maintenance::listClientAccount(std::vector<std::shared_ptr<IAccount>> const& accounts) {
+        for(int i = 0; i < accounts.size(); ++i) {
+            std::cout << "Account nr " << i << ". Client: " << accounts[i]->getDetails() << std::endl;
+        }
+    }
+
+    std::vector<std::shared_ptr<IAccount>> Maintenance::findClientAccounts(unsigned int const clientId) {
+        std::vector<std::shared_ptr<IAccount>> matches;
+        std::copy_if(std::begin(m_accounts), std::end(m_accounts), std::back_inserter(matches),
+            [&] (std::shared_ptr<IAccount> const& account){ return clientId == account->getUserId();});
```
Comment (IllidanSR) [inline banking_system/maintenance.cpp]: try to avoid use & or = in lambda, catching all values can give some unexpected side effects

File: banking_system/maintenance.cpp [hunk 10]
```diff
@@ -0,0 +1,62 @@
...
+    void Maintenance::addAccount(std::shared_ptr<IAccount> account) {
+        m_accounts.push_back(std::move(account));
+    }
+
+    std::shared_ptr<Person> Maintenance::getClient(unsigned int clientId) const {
+        auto const it =  std::find_if(m_clients.begin(), m_clients.end(),
+            [=](std::shared_ptr<Person> const& client){ return clientId == client->id;});
+        if(it != std::end(m_clients))
+            return *it;
+        return nullptr;
```
Comment (IllidanSR) [inline banking_system/maintenance.cpp]: For future changes - let's not return nullptr, but raise exception for such cases

File: banking_system/maintenance.cpp [hunk 11]
```diff
@@ -0,0 +1,62 @@
...
+    }
+
+    std::unique_ptr<IManager> Maintenance::createAccountManager(std::shared_ptr<IAccount> const& account) {
+        if (account->accountType == IAccount::AccountType::Standard) {
+            return std::make_unique<StandardAccountManager>();
+        }
+        else {
```
Comment (IllidanSR) [inline banking_system/maintenance.cpp]: Else not required after return, it can be just return

File: banking_system/maintenance.h [hunk 12]
```diff
@@ -0,0 +1,25 @@
...
+    class Maintenance {
+    private:
+        std::vector<std::shared_ptr<Person>> m_clients;
+        std::vector<std::shared_ptr<IAccount>> m_accounts;
+    public:
+        Maintenance();
+
+        void listClients() const;
+        static void listClientAccount(std::vector<std::shared_ptr<IAccount>> const& accounts) ;
+        std::vector<std::shared_ptr<IAccount>> findClientAccounts(unsigned int clientId);
```
Comment (IllidanSR) [inline banking_system/maintenance.h]: Here and above, const modifications for base type have no effects in headers and can be placed only in .cpp files

**Review by IllidanSR — CHANGES_REQUESTED** [review]

File: banking_system/funds_pln.h [hunk 13]
```diff
@@ -0,0 +1,15 @@
...
+#include "funds.h"
+
+namespace bank {
+    class FundsPLN: public Funds {
+    public:
+        explicit FundsPLN(double const amountOfMoney): Funds(amountOfMoney) {}
+
+        double convertToPLN() override;
+        double convertToUSD() override;
+        double convertToEUR() override;
```
Comment (IllidanSR) [inline banking_system/funds_pln.h]: Look's like can be const here and above

File: banking_system/interfaces/i_manager.h [hunk 14]
```diff
@@ -0,0 +1,20 @@
...
+#include "i_funds.h"
+#include "../person.h"
+
+namespace bank {
+    class IManager {
+    public:
+        virtual ~IManager() = default;
+
+        virtual std::string getAccountDetails(std::unique_ptr<IAccount> const& account) = 0;
+        virtual std::unique_ptr<IAccount> createAccount(std::shared_ptr<Person> person, std::unique_ptr<IFunds> funds) = 0;
```
Comment (IllidanSR) [inline banking_system/interfaces/i_manager.h:16]: Let's use alias for unique_ptr type with signature IAccountPtr

File: banking_system/maintenance.cpp [hunk 15]
```diff
@@ -0,0 +1,74 @@
...
+
+namespace bank {
+    Maintenance::Maintenance() {
+        m_clients = std::vector<std::shared_ptr<Person>>();
+        m_accounts = std::vector<std::unique_ptr<IAccount>>();
+    }
+
+    void Maintenance::listClients() const {
+        if (m_clients.empty())
+            throw exceptions::NoClientsPresent();
```
Comment (IllidanSR) [inline banking_system/maintenance.cpp]: Please use braces for all cases

File: banking_system/exceptions/exception.h [hunk 16]
```diff
@@ -0,0 +1,14 @@
...
+#include <exception>
+#include <string>
+
+namespace exceptions {
+    class Exception: public std::exception {
+    public:
+        explicit Exception() :m_message( "Exception raised! Details: ") {}
+        char const* what() const noexcept override { return m_message.c_str(); }
+    protected:
+        std::string m_message;
```
Comment (IllidanSR) [inline banking_system/exceptions/exception.h:12]: We can avoid to use protected field here, just use constructor with parameter, that takes error message and put it into field, and all derived classes can call in initialisation list just Exception(message)

File: banking_system/exceptions/exception.h [hunk 17]
```diff
@@ -0,0 +1,14 @@
+#pragma once
+
+#include <exception>
+#include <string>
+
+namespace exceptions {
+    class Exception: public std::exception {
+    public:
+        explicit Exception() :m_message( "Exception raised! Details: ") {}
```
Comment (IllidanSR) [inline banking_system/exceptions/exception.h]: explicit not required for default constructor

File: banking_system/exceptions/exception.h [hunk 18]
```diff
@@ -0,0 +1,14 @@
...
+        char const* what() const noexcept override { return m_message.c_str(); }
```
Comment (IllidanSR) [inline banking_system/exceptions/exception.h]: For not template class I suggest to move implementation into .cpp file

File: banking_system/maintenance.cpp [hunk 19]
```diff
@@ -0,0 +1,74 @@
...
+#include "standard_account_manager.h"
+#include "exceptions/client_not_found.h"
+#include "exceptions/no_accounts_found_for_given_client_id.h"
+#include "exceptions/no_clients_present.h"
+
+
+namespace bank {
+    Maintenance::Maintenance() {
+        m_clients = std::vector<std::shared_ptr<Person>>();
+        m_accounts = std::vector<std::unique_ptr<IAccount>>();
```
Comment (IllidanSR) [inline banking_system/maintenance.cpp]: Let's use init list or default initialisation

File: banking_system/maintenance.cpp [hunk 20]
```diff
@@ -0,0 +1,74 @@
...
+        }
+    }
+
+    void Maintenance::listClientAccounts(std::vector<std::vector<std::unique_ptr<IAccount>>::iterator> const& accounts) {
+        for(int i = 0; i < accounts.size(); ++i) {
+            std::cout << "Account nr " << i << ". Client: " << (*accounts[i])->getDetails() << std::endl;
+        }
+    }
+
+    std::vector<std::vector<std::unique_ptr<IAccount>>::iterator> Maintenance::findClientAccounts(unsigned int const clientId) {
```
Comment (IllidanSR) [inline banking_system/maintenance.cpp]: why we use here nested vector? Can we use such approach:
```cpp
std::vector<std::unique_ptr<IAccount>>::iterator Maintenance::findClientAccount(unsigned int const clientId) {
    auto isClientAccount = &clientId {
        return clientId == account->getUserId();
    };

    auto it = std::find_if(m_accounts.begin(), m_accounts.end(), isClientAccount);
    if (it == m_accounts.end()) {
        throw exceptions::NoAccountFoundForGivenClientId();
    }

    return it;
}
```

Comment (IllidanSR) [reply banking_system/maintenance.cpp]: As well, I suggest to not return iterator to structure inside class, because when client code will try to use it - it can be change and we will have invalid iterator. Better option - return value, or iterator that can store value inside some how.

**Review by IllidanSR — CHANGES_REQUESTED** [review]

File: banking_system/maintenance.cpp (hunk 19 above)
Comment (IllidanSR) [reply banking_system/maintenance.cpp]: Updated

**Review by IllidanSR — APPROVED** [review]
